language: minimal

env:
    - CODECOV_TOKEN="c51b1965-fd46-4c03-b4e4-2b22d03d033e"

python:
    - "3.9"

services:
    - docker

script:
    - docker-compose run api bash -c "source /migrate.sh"
    - docker-compose run api flake8
    - docker-compose run api sh -c "coverage run --source='.' manage.py test && coverage xml"

after_success:
    - bash <(curl -s https://codecov.io/bash)
