version: "3.7"

services:
    api:
        container_name: api
        build:
            context: ./src
            dockerfile: build/dev/Dockerfile
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=devpassword
        expose:
            - 8000
        volumes:
            - ./src:/code
            - static_volume:/code/staticfiles
#            - media_volume:/code/media
        command: /start_dev.sh
        depends_on:
            - postgres

    postgres:
        container_name: postgres
        image: postgres:12.0-alpine
        environment:
            - POSTGRES_DB=django_rest_starter
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=devpassword
        ports:
            - 5444:5432 # this is not used by other containers, its purpose is to be able to query the database from outside easily
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    nginx:
        build:
            context: server/dev
        container_name: server
        ports:
            - 8000:80
        volumes:
            - static_volume:/home/app/web/static
#            - media_volume:/home/app/web/media
        depends_on:
            - api


volumes:
    postgres_data:
    static_volume:
#    media_volume:
